base.url=https://rickandmortyapi.com/api
baseAuth.url=http://localhost:8080/api/
register.url=http://localhost:8080/api/register
login.url=http://localhost:8080/api/login
logout.url=http://localhost:8080/api/logout